// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"HelloWorld/internal/config"
	"HelloWorld/internal/dao"
	"HelloWorld/internal/repo"
	"HelloWorld/internal/server"
	"HelloWorld/internal/service"
)

// Injectors from wrie.go:

func InitServer(configPath string) (*server.Server, func(), error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return nil, nil, err
	}
	daoDao, cleanup, err := dao.NewDao(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepo, err := repo.NewUserRepo(daoDao)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceService, cleanup2, err := service.NewService(userRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serverServer, cleanup3, err := server.NewSever(serviceService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return serverServer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
